# Project configuration list
projects:
  - project_name: Xray
    repo_latest: XTLS/Xray-core
    repo_current: jerryin/xray
    version_source:
      latest: github_api
      current: docker_hub
    version_type: semver
    file_path: xray
    repository: xray
    platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7

  - project_name: ZeroTier
    repo_latest: zerotier/ZeroTierOne
    repo_current: jerryin/zerotier
    version_source:
      latest: github_api
      current: docker_hub
    version_type: semver
    file_path: zerotier
    repository: zerotier
    platforms: linux/amd64,linux/arm64

  - project_name: ZeroTier Moon
    repo_latest: zerotier/ZeroTierOne
    repo_current: jerryin/zerotier-moon
    version_source:
      latest: github_api
      current: docker_hub
    version_type: semver
    file_path: zerotier-moon
    repository: zerotier-moon
    platforms: linux/amd64,linux/arm64

  - project_name: New-API
    repo_latest: QuantumNous/new-api
    repo_current: jerryin/new-api
    version_source:
      latest: github_api
      current: docker_hub
      stable_only: true
    version_type: semver
    file_path: new-api
    repository: new-api
    platforms: linux/amd64,linux/arm64
